### ISSUE TITLE
Cache deps for DENO

### ISSUE THREAD

**Issue by vikiival** [vikiival/runners#3]
https://dev.to/craigmorten/github-actions-with-deno-5fnd#comment-25424

```yml
name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DENO_VERSION: "1.30.3"
  DENO_DIR: ~/.deno-cache

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v3
      - name: Use Deno Version ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Lint Deno Module
        run: deno fmt --check
      # Follows https://deno.land/manual@v1.30.1/advanced/continuous_integration#caching-dependencies
      # but use the latest cache@v3
      - name: Cache Deno dependencies 
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      - name: Run Deno Tests
        run: deno test --allow-read --allow-env
```
